"""initial tables

Revision ID: 36304f572c92
Revises: 
Create Date: 2026-01-18 21:50:20.676438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36304f572c92'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keywords_word'), 'keywords', ['word'], unique=True)
    op.create_table('news_items',
    sa.Column('news_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('news_id')
    )
    op.create_index('idx_news_published', 'news_items', ['published_at'], unique=False)
    op.create_index('idx_news_source', 'news_items', ['source'], unique=False)
    op.create_index(op.f('ix_news_items_news_id'), 'news_items', ['news_id'], unique=False)
    op.create_index(op.f('ix_news_items_published_at'), 'news_items', ['published_at'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Enum('SITE', 'TELEGRAM', name='sourcetype', native_enum=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=300), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('news_id', sa.String(length=36), nullable=False),
    sa.Column('generated_text', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'GENERATED', 'PUBLISHED', 'FAILED', name='poststatus', native_enum=False), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news_items.news_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_post_news_id', 'posts', ['news_id'], unique=False)
    op.create_index('idx_post_published', 'posts', ['published_at'], unique=False)
    op.create_index('idx_post_status', 'posts', ['status'], unique=False)
    op.create_index(op.f('ix_posts_news_id'), 'posts', ['news_id'], unique=False)
    op.create_index(op.f('ix_posts_published_at'), 'posts', ['published_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_published_at'), table_name='posts')
    op.drop_index(op.f('ix_posts_news_id'), table_name='posts')
    op.drop_index('idx_post_status', table_name='posts')
    op.drop_index('idx_post_published', table_name='posts')
    op.drop_index('idx_post_news_id', table_name='posts')
    op.drop_table('posts')
    op.drop_table('sources')
    op.drop_index(op.f('ix_news_items_published_at'), table_name='news_items')
    op.drop_index(op.f('ix_news_items_news_id'), table_name='news_items')
    op.drop_index('idx_news_source', table_name='news_items')
    op.drop_index('idx_news_published', table_name='news_items')
    op.drop_table('news_items')
    op.drop_index(op.f('ix_keywords_word'), table_name='keywords')
    op.drop_table('keywords')
    # ### end Alembic commands ###
